### ISSUE TITLE
Рефакторинг-1

### ISSUE THREAD

**Issue by livello** [rombrew/phobia#2]
Как насчет констант в отдельном заголовочном файле или хотя бы в начале?
https://github.com/rombrew/phobia/blob/af5e5eee18c00dbcd0523b909f7bfba45ef8532e/src/phobia/pm.c#LL8C27-L8C27

**Comment by rombrew** [comment]
Эти константы выводятся из числа фаз, но не хотелось бы sqrtf там, вызов будет в runtime. Может комментарием выражение для расчета константы указать?

**Comment by livello** [comment]
@rombrew вам виднее. Бросилось в глаза. Обычно такое не встречается в коде, а все константы выносятся.
